name: modulename_server
description: Starting point for a Serverpod module.
resolution: workspace

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: SERVERPOD_VERSION
