name: projectname_server
description: Starting point for a Serverpod server.
resolution: workspace
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: SERVERPOD_VERSION
