name: modulename_client
description: Starting point for a Serverpod module client.
resolution: workspace
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  serverpod_client: 2.9.1
